# Site settings
title: Boyce's Blog
description: "A minimal blog template, build with Jekyll."
url: "http://www.jacoporabolini.com/emerald"
author:
  name: "Boyce Zhang"
  url: "https://github.com/zhangboyce"

# Build settings
baseurl: / #Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Custom variables
version: "1.0.1"
